library(shiny)
source("helper.R")
inputData <-read.csv("data/demo.csv",encoding = 'UTF-8')
shinyServer(
  function(input,output){
    output$resetable_input <- renderUI({
      times <- input$reset_input
      div(id=letters[(times %% length(letters)) + 1],
          textInput("title",label="Customized Title"),
          column(6,numericInput("Alabama",label="Alabama",value=0)),
          column(6,numericInput("Alaska",label="Alaska",value=0)),
          column(6,numericInput("Arizona",label="Arizona",value=0)),
          column(6,numericInput("Arkansas",label="Arkansas",value=0)),
          column(6,numericInput("California",label="California",value=0)),
          column(6,numericInput("Colorado",label="Colorado",value=0)),
          column(6,numericInput("Connecticut",label="Connecticut",value=0)),
          column(6,numericInput("Delaware",label="Delaware",value=0)),
          column(6,numericInput("Florida",label="Florida",value=0)),
          column(6,numericInput("Georgia",label="Georgia",value=0)),
          column(6,numericInput("Hawaii",label="Hawaii",value=0)),
          column(6,numericInput("Idaho",label="Idaho",value=0)),
          column(6,numericInput("Illinois",label="Illinois",value=0)),
          column(6,numericInput("Indiana",label="Indiana",value=0)),
          column(6,numericInput("Iowa",label="Iowa",value=0)),
          column(6,numericInput("Kansas",label="Kansas",value=0)),
          column(6,numericInput("Kentucky",label="Kentucky",value=0)),
          column(6,numericInput("Louisiana",label="Louisiana",value=0)),
          column(6,numericInput("Maine",label="Maine",value=0)),
          column(6,numericInput("Maryland",label="Maryland",value=0)),
          column(6,numericInput("Massachusetts",label="Massachusetts",value=0)),
          column(6,numericInput("Michigan",label="Michigan",value=0)),
          column(6,numericInput("Minnesota",label="Minnesota",value=0)),
          column(6,numericInput("Mississippi",label="Mississippi",value=0)),
          column(6,numericInput("Missouri",label="Missouri",value=0)),
          column(6,numericInput("Montana",label="Montana",value=0)),
          column(6,numericInput("Nebraska",label="Nebraska",value=0)),
          column(6,numericInput("Nevada",label="Nevada",value=0)),
          column(6,numericInput("New Hampshire",label="New Hampshire",value=0)),
          column(6,numericInput("New Jersey",label="New Jersey",value=0)),
          column(6,numericInput("New Mexico",label="New Mexico",value=0)),
          column(6,numericInput("New York",label="New York",value=0)),
          column(6,numericInput("North Carolina",label="North Carolina",value=0)),
          column(6,numericInput("North Dakota",label="North Dakota",value=0)),
          column(6,numericInput("Ohio",label="Ohio",value=0)),
          column(6,numericInput("Oklahoma",label="Oklahoma",value=0)),
          column(6,numericInput("Oregon",label="Oregon",value=0)),
          column(6,numericInput("Pennsylvania",label="Pennsylvania",value=0)),
          column(6,numericInput("Rhode Island",label="Rhode Island",value=0)),
          column(6,numericInput("South Carolina",label="South Carolina",value=0)),
          column(6,numericInput("South Dakota",label="South Dakota",value=0)),
          column(6,numericInput("Tennessee",label="Tennessee",value=0)),
          column(6,numericInput("Texas",label="Texas",value=0)),
          column(6,numericInput("Utah",label="Utah",value=0)),
          column(6,numericInput("Vermont",label="Vermont",value=0)),
          column(6,numericInput("Virginia",label="Virginia",value=0)),
          column(6,numericInput("Washington",label="Washington",value=0)),
          column(6,numericInput("West Virginia",label="West Virginia",value=0)),
          column(6,numericInput("Wisconsin",label="Wisconsin",value=0)),
          column(6,numericInput("Wyoming",label="Wyoming",value=0)))
          

    })
    
    
    output$map <- renderPlot({
      stateName <-switch(input$var,
                        "Total population (06.2015)"=inputData$State,
                        "House seat number"=inputData$State,
                        "Use my own data"=c('Alabama',
                                            'Alaska',
                                            'Arizona',
                                            'Arkansas',
                                            'California',
                                            'Colorado',
                                            'Connecticut',
                                            'Delaware',
                                            'Florida',
                                            'Georgia',
                                            'Hawaii',
                                            'Idaho',
                                            'Illinois',
                                            'Indiana',
                                            'Iowa',
                                            'Kansas',
                                            'Kentucky',
                                            'Louisiana',
                                            'Maine',
                                            'Maryland',
                                            'Massachusetts',
                                            'Michigan',
                                            'Minnesota',
                                            'Mississippi',
                                            'Missouri',
                                            'Montana',
                                            'Nebraska',
                                            'Nevada',
                                            'New Hampshire',
                                            'New Jersey',
                                            'New Mexico',
                                            'New York',
                                            'North Carolina',
                                            'North Dakota',
                                            'Ohio',
                                            'Oklahoma',
                                            'Oregon',
                                            'Pennsylvania',
                                            'Rhode Island',
                                            'South Carolina',
                                            'South Dakota',
                                            'Tennessee',
                                            'Texas',
                                            'Utah',
                                            'Vermont',
                                            'Virginia',
                                            'Washington',
                                            'West Virginia',
                                            'Wisconsin',
                                            'Wyoming'
                                            )
        
      )
      colorPram <- input$colors 
      stateData <- switch(input$var,
          "Total population (06.2015)"=inputData$Population_06.2015,
          "House seat number"=inputData$House_seat_number,
          "Use my own data"=c(input$Alabama,
                              input$Alaska,
                              input$Arizona,
                              input$Arkansas,
                              input$California,
                              input$Colorado,
                              input$Connecticut,
                              input$Delaware,
                              input$Florida,
                              input$Georgia,
                              input$Hawaii,
                              input$Idaho,
                              input$Illinois,
                              input$Indiana,
                              input$Iowa,
                              input$Kansas,
                              input$Kentucky,
                              input$Louisiana,
                              input$Maine,
                              input$Maryland,
                              input$Massachusetts,
                              input$Michigan,
                              input$Minnesota,
                              input$Mississippi,
                              input$Missouri,
                              input$Montana,
                              input$Nebraska,
                              input$Nevada,
                              input$'New Hampshire',
                              input$'New Jersey',
                              input$'New Mexico',
                              input$'New York',
                              input$'North Carolina',
                              input$'North Dakota',
                              input$Ohio,
                              input$Oklahoma,
                              input$Oregon,
                              input$Pennsylvania,
                              input$'Rhode Island',
                              input$'South Carolina',
                              input$'South Dakota',
                              input$Tennessee,
                              input$Texas,
                              input$Utah,
                              input$Vermont,
                              input$Virginia,
                              input$Washington,
                              input$'West Virginia',
                              input$Wisconsin,
                              input$Wyoming
                              )

                         )
      maptitle <- switch(input$var,
                         "Total population (06.2015)"="Total population (06.2015)",
                         "House seat number"="House seat number",
                         "Use my own data"=input$title)
      
      plotMap(stateName,stateData,maptitle,colorPram)
    })

  }
)



